apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiehub-live-deployment
  labels:
    app: eddiehub-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eddiehub-live
  template:
    metadata:
      labels:
        app: eddiehub-live
    spec:
      containers:
        - name: api
          image: ghcr.io/eddiehubcommunity/live:latest
          ports:
            - containerPort: 5000
